[09:40:46.045] [ERROR] - com.github.wasiqb.coteafs.appium.error.DeviceDriverInitializationFailedError: Error occured while initializing device driver. (ErrorUtils:) 
[09:40:46.048] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.048] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.048] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.049] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.049] [ERROR] - 	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:102) (ErrorUtils:) 
[09:40:46.049] [ERROR] - 	at com.github.wasiqb.coteafs.error.util.ErrorUtil.fail(ErrorUtil.java:70) (ErrorUtils:) 
[09:40:46.049] [ERROR] - 	at com.github.wasiqb.coteafs.appium.utils.ErrorUtils.fail(ErrorUtils.java:53) (ErrorUtils:) 
[09:40:46.050] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.init(Device.java:272) (ErrorUtils:) 
[09:40:46.050] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.startDriver(Device.java:406) (ErrorUtils:) 
[09:40:46.050] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.start(Device.java:185) (ErrorUtils:) 
[09:40:46.051] [ERROR] - 	at com.jtv.tests.getStartedTest.setupTest(getStartedTest.java:49) (ErrorUtils:) 
[09:40:46.051] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.051] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.052] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.052] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.053] [ERROR] - 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) (ErrorUtils:) 
[09:40:46.053] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523) (ErrorUtils:) 
[09:40:46.053] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224) (ErrorUtils:) 
[09:40:46.053] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146) (ErrorUtils:) 
[09:40:46.054] [ERROR] - 	at org.testng.TestRunner.beforeRun(TestRunner.java:626) (ErrorUtils:) 
[09:40:46.054] [ERROR] - 	at org.testng.TestRunner.run(TestRunner.java:594) (ErrorUtils:) 
[09:40:46.054] [ERROR] - 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) (ErrorUtils:) 
[09:40:46.055] [ERROR] - 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) (ErrorUtils:) 
[09:40:46.055] [ERROR] - 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) (ErrorUtils:) 
[09:40:46.055] [ERROR] - 	at org.testng.SuiteRunner.run(SuiteRunner.java:289) (ErrorUtils:) 
[09:40:46.056] [ERROR] - 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) (ErrorUtils:) 
[09:40:46.056] [ERROR] - 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) (ErrorUtils:) 
[09:40:46.056] [ERROR] - 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) (ErrorUtils:) 
[09:40:46.056] [ERROR] - 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) (ErrorUtils:) 
[09:40:46.057] [ERROR] - 	at org.testng.TestNG.runSuites(TestNG.java:1144) (ErrorUtils:) 
[09:40:46.057] [ERROR] - 	at org.testng.TestNG.run(TestNG.java:1115) (ErrorUtils:) 
[09:40:46.057] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178) (ErrorUtils:) 
[09:40:46.058] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92) (ErrorUtils:) 
[09:40:46.058] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96) (ErrorUtils:) 
[09:40:46.058] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.058] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.059] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.059] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.059] [ERROR] - 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) (ErrorUtils:) 
[09:40:46.059] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159) (ErrorUtils:) 
[09:40:46.060] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87) (ErrorUtils:) 
[09:40:46.060] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) (ErrorUtils:) 
[09:40:46.060] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) (ErrorUtils:) 
[09:40:46.060] [ERROR] - Caused by: (ErrorUtils:) 
[09:40:46.061] [ERROR] - java.lang.reflect.InvocationTargetException (ErrorUtils:) 
[09:40:46.061] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.061] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.061] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.062] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.062] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.init(Device.java:268) (ErrorUtils:) 
[09:40:46.062] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.startDriver(Device.java:406) (ErrorUtils:) 
[09:40:46.062] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.start(Device.java:185) (ErrorUtils:) 
[09:40:46.062] [ERROR] - 	at com.jtv.tests.getStartedTest.setupTest(getStartedTest.java:49) (ErrorUtils:) 
[09:40:46.063] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.063] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.063] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.063] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.064] [ERROR] - 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) (ErrorUtils:) 
[09:40:46.064] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523) (ErrorUtils:) 
[09:40:46.064] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224) (ErrorUtils:) 
[09:40:46.064] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146) (ErrorUtils:) 
[09:40:46.065] [ERROR] - 	at org.testng.TestRunner.beforeRun(TestRunner.java:626) (ErrorUtils:) 
[09:40:46.065] [ERROR] - 	at org.testng.TestRunner.run(TestRunner.java:594) (ErrorUtils:) 
[09:40:46.065] [ERROR] - 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) (ErrorUtils:) 
[09:40:46.065] [ERROR] - 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) (ErrorUtils:) 
[09:40:46.065] [ERROR] - 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) (ErrorUtils:) 
[09:40:46.066] [ERROR] - 	at org.testng.SuiteRunner.run(SuiteRunner.java:289) (ErrorUtils:) 
[09:40:46.066] [ERROR] - 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) (ErrorUtils:) 
[09:40:46.066] [ERROR] - 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) (ErrorUtils:) 
[09:40:46.066] [ERROR] - 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) (ErrorUtils:) 
[09:40:46.067] [ERROR] - 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) (ErrorUtils:) 
[09:40:46.067] [ERROR] - 	at org.testng.TestNG.runSuites(TestNG.java:1144) (ErrorUtils:) 
[09:40:46.067] [ERROR] - 	at org.testng.TestNG.run(TestNG.java:1115) (ErrorUtils:) 
[09:40:46.067] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178) (ErrorUtils:) 
[09:40:46.068] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92) (ErrorUtils:) 
[09:40:46.068] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96) (ErrorUtils:) 
[09:40:46.068] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.068] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.069] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.069] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.069] [ERROR] - 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) (ErrorUtils:) 
[09:40:46.069] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159) (ErrorUtils:) 
[09:40:46.070] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87) (ErrorUtils:) 
[09:40:46.070] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) (ErrorUtils:) 
[09:40:46.070] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) (ErrorUtils:) 
[09:40:46.070] [ERROR] - Caused by: (ErrorUtils:) 
[09:40:46.071] [ERROR] - org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/sedmad1/Library/Android/sdk/platform-tools/adb -P 5037 -s 98892a383146365553 shell pm install -r /data/local/tmp/appium_cache/622d2cfc168662f5acdf867a1ad1e5ca927233be.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'l4024.jewelry.acn', ip: 'fe80:0:0:0:866:4baf:2d32:77c5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_212'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/sedmad1/Library/Android/sdk/platform-tools/adb -P 5037 -s 98892a383146365553 shell pm install -r /data/local/tmp/appium_cache/622d2cfc168662f5acdf867a1ad1e5ca927233be.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'l4024.jewelry.acn', ip: 'fe80:0:0:0:866:4baf:2d32:77c5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_212'
Driver info: driver.version: AndroidDriver (ErrorUtils:) 
[09:40:46.071] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208) (ErrorUtils:) 
[09:40:46.072] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217) (ErrorUtils:) 
[09:40:46.072] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239) (ErrorUtils:) 
[09:40:46.072] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) (ErrorUtils:) 
[09:40:46.072] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42) (ErrorUtils:) 
[09:40:46.073] [ERROR] - 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) (ErrorUtils:) 
[09:40:46.073] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) (ErrorUtils:) 
[09:40:46.073] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) (ErrorUtils:) 
[09:40:46.073] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) (ErrorUtils:) 
[09:40:46.074] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38) (ErrorUtils:) 
[09:40:46.074] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84) (ErrorUtils:) 
[09:40:46.074] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94) (ErrorUtils:) 
[09:40:46.074] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95) (ErrorUtils:) 
[09:40:46.074] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.075] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.075] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.075] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.075] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.init(Device.java:268) (ErrorUtils:) 
[09:40:46.076] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.startDriver(Device.java:406) (ErrorUtils:) 
[09:40:46.076] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.start(Device.java:185) (ErrorUtils:) 
[09:40:46.076] [ERROR] - 	at com.jtv.tests.getStartedTest.setupTest(getStartedTest.java:49) (ErrorUtils:) 
[09:40:46.076] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.076] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.077] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.077] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.077] [ERROR] - 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) (ErrorUtils:) 
[09:40:46.077] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523) (ErrorUtils:) 
[09:40:46.078] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224) (ErrorUtils:) 
[09:40:46.078] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146) (ErrorUtils:) 
[09:40:46.078] [ERROR] - 	at org.testng.TestRunner.beforeRun(TestRunner.java:626) (ErrorUtils:) 
[09:40:46.078] [ERROR] - 	at org.testng.TestRunner.run(TestRunner.java:594) (ErrorUtils:) 
[09:40:46.078] [ERROR] - 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) (ErrorUtils:) 
[09:40:46.079] [ERROR] - 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) (ErrorUtils:) 
[09:40:46.079] [ERROR] - 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) (ErrorUtils:) 
[09:40:46.079] [ERROR] - 	at org.testng.SuiteRunner.run(SuiteRunner.java:289) (ErrorUtils:) 
[09:40:46.080] [ERROR] - 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) (ErrorUtils:) 
[09:40:46.080] [ERROR] - 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) (ErrorUtils:) 
[09:40:46.080] [ERROR] - 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) (ErrorUtils:) 
[09:40:46.080] [ERROR] - 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) (ErrorUtils:) 
[09:40:46.080] [ERROR] - 	at org.testng.TestNG.runSuites(TestNG.java:1144) (ErrorUtils:) 
[09:40:46.081] [ERROR] - 	at org.testng.TestNG.run(TestNG.java:1115) (ErrorUtils:) 
[09:40:46.081] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178) (ErrorUtils:) 
[09:40:46.081] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92) (ErrorUtils:) 
[09:40:46.081] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96) (ErrorUtils:) 
[09:40:46.082] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.082] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.082] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.082] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.082] [ERROR] - 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) (ErrorUtils:) 
[09:40:46.083] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159) (ErrorUtils:) 
[09:40:46.083] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87) (ErrorUtils:) 
[09:40:46.083] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) (ErrorUtils:) 
[09:40:46.083] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) (ErrorUtils:) 
[09:40:46.083] [ERROR] - Caused by: (ErrorUtils:) 
[09:40:46.084] [ERROR] - java.lang.reflect.InvocationTargetException (ErrorUtils:) 
[09:40:46.084] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.084] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.084] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.084] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.085] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186) (ErrorUtils:) 
[09:40:46.085] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217) (ErrorUtils:) 
[09:40:46.085] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239) (ErrorUtils:) 
[09:40:46.085] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) (ErrorUtils:) 
[09:40:46.086] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42) (ErrorUtils:) 
[09:40:46.086] [ERROR] - 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) (ErrorUtils:) 
[09:40:46.086] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) (ErrorUtils:) 
[09:40:46.086] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) (ErrorUtils:) 
[09:40:46.086] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) (ErrorUtils:) 
[09:40:46.087] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38) (ErrorUtils:) 
[09:40:46.087] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84) (ErrorUtils:) 
[09:40:46.087] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94) (ErrorUtils:) 
[09:40:46.087] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95) (ErrorUtils:) 
[09:40:46.087] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.088] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.088] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.088] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.088] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.init(Device.java:268) (ErrorUtils:) 
[09:40:46.089] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.startDriver(Device.java:406) (ErrorUtils:) 
[09:40:46.089] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.start(Device.java:185) (ErrorUtils:) 
[09:40:46.089] [ERROR] - 	at com.jtv.tests.getStartedTest.setupTest(getStartedTest.java:49) (ErrorUtils:) 
[09:40:46.089] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.089] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.090] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.090] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.090] [ERROR] - 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) (ErrorUtils:) 
[09:40:46.090] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523) (ErrorUtils:) 
[09:40:46.090] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224) (ErrorUtils:) 
[09:40:46.091] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146) (ErrorUtils:) 
[09:40:46.091] [ERROR] - 	at org.testng.TestRunner.beforeRun(TestRunner.java:626) (ErrorUtils:) 
[09:40:46.091] [ERROR] - 	at org.testng.TestRunner.run(TestRunner.java:594) (ErrorUtils:) 
[09:40:46.091] [ERROR] - 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) (ErrorUtils:) 
[09:40:46.091] [ERROR] - 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) (ErrorUtils:) 
[09:40:46.092] [ERROR] - 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) (ErrorUtils:) 
[09:40:46.092] [ERROR] - 	at org.testng.SuiteRunner.run(SuiteRunner.java:289) (ErrorUtils:) 
[09:40:46.092] [ERROR] - 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) (ErrorUtils:) 
[09:40:46.092] [ERROR] - 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) (ErrorUtils:) 
[09:40:46.092] [ERROR] - 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) (ErrorUtils:) 
[09:40:46.093] [ERROR] - 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) (ErrorUtils:) 
[09:40:46.093] [ERROR] - 	at org.testng.TestNG.runSuites(TestNG.java:1144) (ErrorUtils:) 
[09:40:46.093] [ERROR] - 	at org.testng.TestNG.run(TestNG.java:1115) (ErrorUtils:) 
[09:40:46.093] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178) (ErrorUtils:) 
[09:40:46.093] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.094] [ERROR] - 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) (ErrorUtils:) 
[09:40:46.095] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159) (ErrorUtils:) 
[09:40:46.095] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87) (ErrorUtils:) 
[09:40:46.095] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) (ErrorUtils:) 
[09:40:46.095] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) (ErrorUtils:) 
[09:40:46.095] [ERROR] - Caused by: (ErrorUtils:) 
[09:40:46.096] [ERROR] - org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/sedmad1/Library/Android/sdk/platform-tools/adb -P 5037 -s 98892a383146365553 shell pm install -r /data/local/tmp/appium_cache/622d2cfc168662f5acdf867a1ad1e5ca927233be.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'l4024.jewelry.acn', ip: 'fe80:0:0:0:866:4baf:2d32:77c5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_212'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/sedmad1/Library/Android/sdk/platform-tools/adb -P 5037 -s 98892a383146365553 shell pm install -r /data/local/tmp/appium_cache/622d2cfc168662f5acdf867a1ad1e5ca927233be.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'androidInstallTimeout' capability
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37) (ErrorUtils:) 
[09:40:46.096] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.096] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.096] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.096] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) (ErrorUtils:) 
[09:40:46.097] [ERROR] - 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) (ErrorUtils:) 
[09:40:46.098] [ERROR] - 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.099] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186) (ErrorUtils:) 
[09:40:46.100] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217) (ErrorUtils:) 
[09:40:46.100] [ERROR] - 	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239) (ErrorUtils:) 
[09:40:46.100] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) (ErrorUtils:) 
[09:40:46.100] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42) (ErrorUtils:) 
[09:40:46.100] [ERROR] - 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) (ErrorUtils:) 
[09:40:46.101] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) (ErrorUtils:) 
[09:40:46.101] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) (ErrorUtils:) 
[09:40:46.101] [ERROR] - 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) (ErrorUtils:) 
[09:40:46.101] [ERROR] - 	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38) (ErrorUtils:) 
[09:40:46.101] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) (ErrorUtils:) 
[09:40:46.102] [ERROR] - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.init(Device.java:268) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.startDriver(Device.java:406) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at com.github.wasiqb.coteafs.appium.device.Device.start(Device.java:185) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at com.jtv.tests.getStartedTest.setupTest(getStartedTest.java:49) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.103] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.104] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.104] [ERROR] - 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108) (ErrorUtils:) 
[09:40:46.104] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523) (ErrorUtils:) 
[09:40:46.104] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224) (ErrorUtils:) 
[09:40:46.104] [ERROR] - 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.TestRunner.beforeRun(TestRunner.java:626) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.TestRunner.run(TestRunner.java:594) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) (ErrorUtils:) 
[09:40:46.105] [ERROR] - 	at org.testng.SuiteRunner.run(SuiteRunner.java:289) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.TestNG.runSuites(TestNG.java:1144) (ErrorUtils:) 
[09:40:46.106] [ERROR] - 	at org.testng.TestNG.run(TestNG.java:1115) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) (ErrorUtils:) 
[09:40:46.107] [ERROR] - 	at java.lang.reflect.Method.invoke(Method.java:498) (ErrorUtils:) 
[09:40:46.108] [ERROR] - 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) (ErrorUtils:) 
[09:40:46.108] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159) (ErrorUtils:) 
[09:40:46.108] [ERROR] - 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87) (ErrorUtils:) 
[09:40:46.108] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) (ErrorUtils:) 
[09:40:46.108] [ERROR] - 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) (ErrorUtils:) 
